# Generated by Django 4.2.5 on 2023-10-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
