# Generated by Django 4.2.5 on 2023-10-18 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_product_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
