# Generated by Django 4.2.5 on 2023-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
