# Generated by Django 4.2.5 on 2023-11-21 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
